# Generated by Django 5.1.1 on 2025-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_profile_code_alter_profile_recommended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='correct_code',
            field=models.TextField(blank=True, default="print('Hello, World!')"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
