# Generated by Django 5.1.1 on 2025-03-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_submission_is_correct_task_correct_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_correct',
        ),
    ]
