# Generated by Django 5.1.1 on 2025-02-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_task_yty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yty',
        ),
    ]
